# Generated by Django 5.1.3 on 2024-11-23 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_id",
            field=models.PositiveIntegerField(default=0, verbose_name="ID товара"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(
                default="unknown", max_length=255, verbose_name="Название товара"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Количество",
            ),
        ),
    ]
