# Generated by Django 5.1.3 on 2024-11-27 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderitem_product_id_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.CharField(
                blank=True,
                help_text="Укажите способ доставки",
                max_length=30,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
