# Generated by Django 5.1.3 on 2024-11-27 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_delivery_alter_order_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата покупки"
            ),
        ),
    ]
