# Generated by Django 5.1.3 on 2024-11-22 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Кол-во товара в наличии",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Кол-во",
            ),
        ),
    ]
