# Generated by Django 5.1.3 on 2024-11-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cost_price",
        ),
    ]
