# Generated by Django 5.1.3 on 2024-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="total_expenses",
            field=models.IntegerField(default=0, verbose_name="Затраты"),
        ),
        migrations.AddField(
            model_name="myuser",
            name="total_revenue",
            field=models.PositiveIntegerField(default=0, verbose_name="Выручка"),
        ),
    ]
