# Generated by Django 5.1.3 on 2024-11-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_myuser_total_expenses_myuser_total_revenue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Необязательное поле",
                max_length=20,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=30, unique=True, verbose_name="Логин"),
        ),
    ]
